// Code generated by wit-bindgen-go. DO NOT EDIT.

package playground

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:playground@0.1.0".

//go:wasmexport process
//export process
func wasmexport_Process(input0 *uint8, input1 uint32) (result *string) {
	input := cm.LiftString[string]((*uint8)(input0), (uint32)(input1))
	result_ := Exports.Process(input)
	result = &result_
	return
}

//go:wasmexport matrix-bench
//export matrix-bench
func wasmexport_MatrixBench(size0 uint32, iterations0 uint32) (result0 uint64) {
	size := (uint32)((uint32)(size0))
	iterations := (uint32)((uint32)(iterations0))
	result := Exports.MatrixBench(size, iterations)
	result0 = (uint64)(result)
	return
}
