// Code generated by wit-bindgen-go. DO NOT EDIT.

package playground

// Exports represents the caller-defined exports from "wasi:playground/playground@0.1.0".
var Exports struct {
	// Process represents the caller-defined, exported function "process".
	//
	//	process: func(input: string) -> string
	Process func(input string) (result string)

	// MatrixBench represents the caller-defined, exported function "matrix-bench".
	//
	// Benchmark matrix multiplication.
	// Multiplies two NxN matrices `iterations` times.
	// Returns total time in nanoseconds.
	//
	//	matrix-bench: func(size: u32, iterations: u32) -> u64
	MatrixBench func(size uint32, iterations uint32) (result uint64)
}
