// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

// This file contains wasmimport and wasmexport declarations for "myapp:component@0.1.0".

//go:wasmimport myapp:component/host@0.1.0 log
//go:noescape
func wasmimport_Log(msg0 *uint8, msg1 uint32)
