// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "wasi:playground/host@0.1.0".
package host

import (
	"go.bytecodealliance.org/cm"
)

// Log represents the imported function "log".
//
//	log: func(msg: string)
//
//go:nosplit
func Log(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Log((*uint8)(msg0), (uint32)(msg1))
	return
}
