// Code generated by wit-bindgen-go. DO NOT EDIT.

package myworld

// Exports represents the caller-defined exports from "myapp:component/my-world@0.1.0".
var Exports struct {
	// Process represents the caller-defined, exported function "process".
	//
	//	process: func(input: string) -> string
	Process func(input string) (result string)
}
