// Code generated by wit-bindgen-go. DO NOT EDIT.

package myworld

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "myapp:component@0.1.0".

//go:wasmexport process
//export process
func wasmexport_Process(input0 *uint8, input1 uint32) (result *string) {
	input := cm.LiftString[string]((*uint8)(input0), (uint32)(input1))
	result_ := Exports.Process(input)
	result = &result_
	return
}
